function NameGen()
{
	
	prefix[0] = "Krumblor, "
	prefix[1] = "Alric, "
	prefix[2] = "Algibert, "
	prefix[3] = "Ordric, "
	prefix[4] = "Eadward, "
	prefix[5] = "Medwin, "
	prefix[6] = "Tilwald, "
	prefix[7] = "Jaenbert, "
	prefix[8] = "Wiermund, "
	prefix[9] = "Cynwulf, "
	prefix[10] = "Eanlac, "
	prefix[11] = "Byrnstan, "
	prefix[12] = "Saebehrt, "
	prefix[13] = "Godwine, "
	prefix[14] = "Calunoth, "
	prefix[15] = "Rhoam, "
	prefix[16] = "Germund, "
	prefix[17] = "Eadger, "
	prefix[18] = "Sigbert, "
	prefix[19] = "Ingwald, "
	prefix[20] = "Osmer, "
	prefix[21] = "Ulfrid, "
	prefix[22] = "Ceolfrid, "
	prefix[23] = "Yharon, "
	prefix[24] = "King Arthur, "
	prefix[25] = "Beauwulf, "
	prefix[26] = "Nerian, "
	
	suffix[0] = "The Ressurected"
	suffix[1] = "The Undying"
	suffix[2] = "The Priest"
	suffix[3] = "The High Priest"
	suffix[4] = "The Awoken"
	suffix[5] = "The Cave Beast"
	suffix[6] = "The Judge"
	suffix[7] = "The Fool"
	suffix[8] = "The Trickster"
	suffix[9] = "The Magus"
	suffix[10] = "The Commander"
	suffix[11] = "The Commander of Beasts"
	suffix[12] = "The Commander of Anguish"
	suffix[13] = "The Commander of Gods"
	suffix[14] = "The Herald"
	suffix[15] = "The Herald of Flesh"
	suffix[16] = "The Herald of Ice"
	suffix[17] = "The Herald of The Moon"
	suffix[18] = "The Rift Herald"
	suffix[19] = "The Apostle of Nightmares"
	suffix[20] = "The Apostle of Ruin"
	suffix[21] = "The Apostle"
	suffix[22] = "The Reckless"
	suffix[23] = "The Destroyer"
	suffix[24] = "The Destroyer of Kingdoms"
	suffix[25] = "The Paragon"
	suffix[26] = "The Paragon of Knowledge"
	suffix[27] = "The Paragon of Power"
	suffix[28] = "The Paragon of Death"
	suffix[29] = "The Overlord"
	suffix[30] = "The Overlord of The Sky"
	suffix[31] = "The Eternal"
	suffix[32] = "The Reborn"
	suffix[33] = "The Betrayed"
	suffix[34] = "The Baron"
	suffix[35] = "The Bishop"
	
	prefixGen = irandom(26)
	suffixGen = irandom(35)
	
	namePrefix = prefix[prefixGen]
	nameSuffix = suffix[suffixGen]
	
	return "<" + namePrefix + nameSuffix + ">"
	
}